server:
  port: 8082
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka/ #注册到刚才那台Eureka Server地址
spring:
  application:
    name: client-1
